### ISSUE TITLE
Example usages for fcl.OcTree

### ISSUE THREAD

**Issue by eaa3** [BerkeleyAutomation/python-fcl#7]
Would it be possible to add tests and examples using fcl.OcTree. Could you give an instantiation example? I assume it should be read from bytes representing an octree. If I give:

`fcl_tree =fcl.OcTree(0.1, data)`

It gives the following error:
`
Traceback (most recent call last):
  File "example1.py", line 20, in <module>
    fcl_tree =fcl.OcTree(0.1, data)
  File "fcl/fcl.pyx", line 403, in fcl.fcl.OcTree.__cinit__
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_char
TypeError: an integer is required
`

**Comment by alphonsusadubredu** [comment]
A way around this could be to convert the octree into boxes and perform collision-detection on the boxes.
Check out this link for an example implementation: [https://github.com/kucars/laser_collision_detection/blob/1b78fe5a95584d135809b1448d33675bb8fee250/src/laser_obstacle_detect.cpp#L252](url)

**Comment by ddm-j** [comment]
I don't have a solution, but I dug this up for other people looking into this: http://library.isr.ist.utl.pt/docs/roswiki/octomap(2f)Tutorials(2f)Creating(20)an(20)OctoMap(20)from(20)existing(20)3D(2028)mesh(2920)data.html

**Comment by zickzeon06** [comment]
@eaa3 @tim-fan @adubredu @ddm-j @zichunxx Hello, I have successfully called pcl.octree. The issue you encountered is due to using
pip install python-fcl
, as the official library does not include methods like insertPointCloud in the octree class, which causes the error
TypeError: cinit() takes exactly 2 positional arguments (1 given).
The editor might find the error to your local project, but the actual file fcl.pyx is located in /home/lu/.local/lib/python3.8/site-packages/fcl (lu is my system name). You can find that it is incomplete there, but please don’t attempt to modify it directly, as it won’t work, and do not update to the official 0.7.0.7 version since it still lacks the relevant content.

First, you need to uninstall the current library with:

pip uninstall python-fcl

Then, download one of these two projects from GitHub:

https://github.com/automatika-robotics/python-fcl
https://github.com/cedriclmenard/python-fcl-octomap

In the project, run
pip install .
to install. Make sure to check your pcl installation location. If you installed it with ROS, you will need to add "/opt/ros/noetic/include" to include_dirs in setup.py to avoid errors. After installation is complete, you can directly use any of the following code snippets to test:

import numpy as np
import fcl

x = np.random.random([100, 3])
resolution = 0.02
object1 = fcl.OcTree(r=0.02, points=x)
object2 = fcl.Box(1, 2, 3)
o1 = fcl.CollisionObject(object1, fcl.Transform())
o2 = fcl.CollisionObject(object2, fcl.Transform())

request = fcl.CollisionRequest()
result = fcl.CollisionResult()

req = fcl.collide(o2, o2, request, result)

print(req)
